# Generated by Django 5.0.7 on 2026-05-26 06:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=64)),
                ('name', models.CharField(max_length=160)),
                ('country', models.CharField(default='India', max_length=64)),
                ('grid_region', models.CharField(blank=True, max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='IngestionBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('received', 'Received'), ('processed', 'Processed'), ('failed', 'Failed')], default='received', max_length=32)),
                ('rows_received', models.PositiveIntegerField(default=0)),
                ('rows_created', models.PositiveIntegerField(default=0)),
                ('errors', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ActivityRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_record_id', models.CharField(max_length=160)),
                ('raw_payload', models.JSONField(default=dict)),
                ('scope', models.CharField(choices=[('scope_1', 'Scope 1'), ('scope_2', 'Scope 2'), ('scope_3', 'Scope 3')], max_length=32)),
                ('activity_type', models.CharField(max_length=80)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('quantity_original', models.DecimalField(blank=True, decimal_places=3, max_digits=14, null=True)),
                ('unit_original', models.CharField(blank=True, max_length=40)),
                ('quantity_normalized', models.DecimalField(blank=True, decimal_places=3, max_digits=14, null=True)),
                ('unit_normalized', models.CharField(blank=True, max_length=40)),
                ('emission_factor', models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True)),
                ('co2e_kg', models.DecimalField(blank=True, decimal_places=3, max_digits=14, null=True)),
                ('confidence_score', models.PositiveSmallIntegerField(default=80)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('needs_attention', 'Needs attention'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('locked', 'Locked')], default='pending', max_length=32)),
                ('flags', models.JSONField(blank=True, default=list)),
                ('review_note', models.TextField(blank=True)),
                ('approved_by', models.CharField(blank=True, max_length=160)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('facility', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_records', to='ingestion.facility')),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_records', to='ingestion.ingestionbatch')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_records', to='ingestion.organization')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddField(
            model_name='ingestionbatch',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='ingestion.organization'),
        ),
        migrations.AddField(
            model_name='facility',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facilities', to='ingestion.organization'),
        ),
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(max_length=64)),
                ('actor', models.CharField(default='system', max_length=160)),
                ('before', models.JSONField(blank=True, default=dict)),
                ('after', models.JSONField(blank=True, default=dict)),
                ('message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='audit_events', to='ingestion.activityrecord')),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='audit_events', to='ingestion.ingestionbatch')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_events', to='ingestion.organization')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='SourceSystem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('source_type', models.CharField(choices=[('sap', 'SAP'), ('utility', 'Utility'), ('travel', 'Travel')], max_length=32)),
                ('connection_mode', models.CharField(max_length=80)),
                ('description', models.TextField(blank=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sources', to='ingestion.organization')),
            ],
        ),
        migrations.AddField(
            model_name='ingestionbatch',
            name='source_system',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='batches', to='ingestion.sourcesystem'),
        ),
        migrations.AddField(
            model_name='activityrecord',
            name='source_system',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='activity_records', to='ingestion.sourcesystem'),
        ),
        migrations.AlterUniqueTogether(
            name='facility',
            unique_together={('organization', 'code')},
        ),
        migrations.AlterUniqueTogether(
            name='activityrecord',
            unique_together={('organization', 'source_system', 'source_record_id')},
        ),
    ]
